### PR TITLE
Wrapper in Bash added- LazyRun.sh and step 4 scripts improved

### PR DESCRIPTION
**Pull request by rrohwer**
So I think this is what your python wrapper did?  But I just made one in bash b/c I can copy-paste commands directly.  Also, it runs through multiple times, running the first run-through alone (as databases are created) and then running the repeated runs with different pidents in paralelle, and only the commands that need to be repeated.  It takes ~ 30 minutes to run, the paralelle thing helps a lot I think.

So the way to integrate the shell script:
- Do step 0 (formatting/naming).
- Shell Script does 1-13 for you, just edit the pidents you want to test.
- Do step 14 individually because it requires analysis of step 13 results.
- Do step 15 when done and satisfied b/c it deletes the extra files.

### CODE REVIEW

**Comment by joshamilton** [comment]
@rrohwer You should really be creating issues when additional work needs to be done. I am leaving this open for now. If you get a chance to fix the R command described in the "NOTE", update your repo and this pull request should update automatically.

**Comment by joshamilton** [comment]
Also the Python wrapper function let you define variables, such as the range of pident's to loop over, organizational structure of your folder, etc. I am a shell newbie, so I don't know if a shell scripts lets you do that.

**Comment by rrohwer** [comment]
- this is up to date and works.
- yes you can specify all the pidents to compare in one place at the top of the bash script, and it takes care of parallelizing the runs and not repeating commands.  So this especially helps when you want to run with 10 different pidents to choose your cutoff.
- if there are future workflow changes, you can just directly copy-paste the new commands into the bash script. format is identical to command line entry.

**Comment by rrohwer** [comment]
The latest commits fix issue #56 

I can't figure out how to make that a separate pull??

**Comment by rrohwer** [comment]
This pull request updates the bash function and updates step 4.

bash: `LazyRun.sh`
- accepts a vector of pidents to test over
  - you have to type those into the script, no command line arguments accepted
    my idea is eventually this will just be our "recommended" easy-run.
- runs subsequent pidents in paralelle, only repeating the necessary commands.

step 4: split the R script `filter_seqIDs_by_pident` into: 
`calc_full_length_pidents.R` and `filter_seqIDs_by_pident.R`
- the calculating a "full length pident" is a separate script now
  - this part takes considerably longer
  - only needs to be run once
    -the filtering by pident is shorter, and just accepts the table generated by the other
  - this run very quickly and is also repeated twice for each pident you try.

@joshamilton now I'm merging it and will use separate branches next time!

**Pull request merged**
