### PR TITLE
small addition

### PR DESCRIPTION
**Pull request by rrohwer**
tiny change to workflow tidy up step 17

### CODE REVIEW

**Comment by joshamilton** [comment]
@rrohwer It looks like you got your pull requests messed up. This request (#80) includes all the commits related to the forcing plots, while request #79 tidies up step 17. Please confirm. I will update your comment and merge.

**Comment by rrohwer** [comment]
I think maybe I screwed up the branches?  Like I meant to pull request from
the "polar" branch for #79 but accidentally pulled from master.  they are
basically the same, I was trying to just add onto the other one with #80.
sorry!

Robin

On Fri, Feb 12, 2016 at 4:20 PM, Joshua J Hamilton <notifications@github.com

**Comment by joshamilton** [comment]
Looks like you still have the `polar` branch. Can you cancel these two pull requests and create a new one from `polar`?

**Comment by rrohwer** [comment]
done.

On Sun, Feb 14, 2016 at 5:13 PM, Joshua J Hamilton <notifications@github.com

**Pull request closed without merging**
