### PR TITLE
New plot added that shows classification improvements achieved using workflow

### PR DESCRIPTION
**Pull request by rrohwer**
It's a new step 16, and a new r script `plot_classification_improvement.R`

It generates two bar plots, one by %OTUS, one by % reads.

two other scripts were modified to export files this new script needs: 
- `find_classification_disagreements.R` modified to 
  - export the p-values-only table for the final taxonomy
  - also apply bootstrap cutoff to the entire general.taxonomy file and then export it's p-values-only table (this does take a bit of extra time, but it only does this when the "final" flag is used in step 15. 
- `plot_classification_disagreements.R` modified to 
  - export the `seqID.reads` variable it already calculated.  this is a list of each seqID and its corresponding total reads, as calculated from the OTU table.

### CODE REVIEW

**Comment by joshamilton** [comment]
@rrohwer Shouldn't there be an update to LazyRun.sh included in this request?

**Comment by rrohwer** [comment]
Good check, but no.  LazyRun is only steps 1-14, because then you have to
look at the plots from step 14 to choose your pident.  Step 15 generates
the final taxonomy file, and this plot is step 16.  I did change something
in step 13's script, but it didn't affect the input arguments at all.
Thanks!

But actually, could you run it tonight and see if it works?  for some
reason I got a ton more database conflicts this time around, and I can't
figure out what changed....  I re-ran old files with the new scripts, and
new files with the old scripts, and I started with the same files as
before.... I haven't figured it out yet.

On Thu, Jan 28, 2016 at 5:00 PM, Joshua J Hamilton <notifications@github.com

**Comment by rrohwer** [comment]
@joshamilton just confirming that this branch works as is, the errors I spoke of above are not errors but in fact corrections!

**Comment by joshamilton** [comment]
@rrohwer Merged. Hooray!

**Comment by rrohwer** [comment]
I hate redpandas now and I hope they go extinct.  My next branch is polar.
Just in case things go as badly, I only have to wait around a little longer
and switch back to incandescent light bulbs.

**Pull request merged**
